### ISSUE TITLE
small bugs with gdb debugserver

### ISSUE THREAD

**Issue by D3Smind** [qilingframework/qiling#254]
On my ubuntu the installer does not copy the qiling/qiling/debugger/gdbserver/xml/ folder when installing and such the gdb debugserver fails.

When debugging PE files with qiling the Server fails at line 128 in the /qiling/blob/master/qiling/debugger/gdbserver/gdbserver.py
`if self.gdb.bp_list in ([self.ql.loader.elf_entry], [self.ql.loader.entry_point]):`
Due to the PE Loader not having a elf_entry.

**Comment by xwings** [comment]
i remember PE works, let me check again.

**Comment by D3Smind** [comment]
I tried again on a clean install. The problem of the missing xmls persists.
gdb> Xml file not found: /usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/debugger/gdbserver/xml/x8664/target.xml

When copy the files manually elf binaries work. The x8664_hello.exe does run but the debugger disconnects and it prints:

> Traceback (most recent call last):
>   File "gdb.py", line 30, in <module>
>     test_gdb(["rootfs/x8664_windows/bin/x8664_hello.exe"], "rootfs/x8664_windows")
>   File "gdb.py", line 26, in test_gdb
>     ql.run()  
>   File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/core.py", line 203, in run
>     self.remotedebugsession.run()
>   File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/debugger/gdbserver/gdbserver.py", line 708, in run
>     commands[cmd](subcmd)
>   File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/debugger/gdbserver/gdbserver.py", line 128, in handle_c
>     if self.gdb.bp_list in ([self.ql.loader.elf_entry], [self.ql.loader.entry_point]):
> AttributeError: 'QlLoaderPE' object has no attribute 'elf_entry'

**Comment by xwings** [comment]
Hi,

Can i know which version of gdb and qiling are u running on. I got a crash and its crash on gdb. not QIling.

**Comment by xwings** [comment]
i add a quick fix in https://github.com/qilingframework/qiling/commit/743cfad06056142e30f78bb984dacae2667361b1

u can clone dev branch and try

**Comment by D3Smind** [comment]
Hi, 

sorry for my bad problem description. The problem with the missing xml files happen with elf and pe emulation&debugging.
In the Manifest the path to the xml folder is broken.

The debugging Problems with PE Files happens when you send a continue command from gdb/idapro the gdbserver trys to get the elf_entry of the QlLoader object for pe (as defined in qiling/loader/pe.py) but QlLoaderPE does not have that attribute.

I have created a pull request with my fixes.
