### ISSUE TITLE
time_ns() is not available in Python 3.6

### ISSUE THREAD

**Issue by cq674350529** [qilingframework/qiling#810]
**Describe the bug**
The syscall implementation for `os/qnx` try to use `time_ns()` in `time` module. However, `time_ns()` is not available in Python 3.6.  
https://github.com/qilingframework/qiling/blob/2eb0547861c470ef6ca3eec1fc66ac03b1dd14b4/qiling/os/qnx/syscall.py#L6

```python
Traceback (most recent call last):
  File "qiling_demo.py", line 1240, in <module>
    qiling_test()
  File "qiling_demo.py", line 1229, in qiling_test
    ql = Qiling([os.path.join(rootfs_path, bin_path), "-d", tar_path], rootfs_path, console=False, verbose=QL_VERBOSE.DEBUG)
  File "~/qiling/qiling/core.py", line 220, in __init__
    self._os = os_setup(self.archtype, self.ostype, self)
  File "~/qiling/qiling/utils.py", line 478, in os_setup
    return ql_get_module_function(f"qiling.os.{ostype_str.lower()}.{ostype_str.lower()}", function_name)(ql)
  File "~/qiling/qiling/utils.py", line 239, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/qiling/qiling/os/linux/linux.py", line 15, in <module>
    from qiling.os.posix.posix import QlOsPosix
  File "~/qiling/qiling/os/posix/posix.py", line 25, in <module>
    from qiling.os.qnx.syscall import *
  File "~/qiling/qiling/os/qnx/syscall.py", line 29, in <module>
    from time import time_ns
ImportError: cannot import name 'time_ns'
```

According to the document, qiling should work with Python 3.5 or above.
> For this installation guide, Ubuntu desktop 18.04.3 LTS 64bit is the base example (Qiling Framework works in other Linux distributions that run Python 3.5 and above)

So, if `time_ns()` is really needed, there is an alternative way for Python 3.6(refering to https://stackoverflow.com/questions/55774054/precise-time-in-nano-seconds-for-python-3-6-and-earlier)

```python
try:
    from time import time_ns
except:
    import ctypes

    CLOCK_REALTIME = 0

    class timespec(ctypes.Structure):
        _fields_ = [
            ('tv_sec', ctypes.c_int64), # seconds, https://stackoverflow.com/q/471248/1672565
            ('tv_nsec', ctypes.c_int64), # nanoseconds
            ]

    clock_gettime = ctypes.cdll.LoadLibrary('libc.so.6').clock_gettime
    clock_gettime.argtypes = [ctypes.c_int64, ctypes.POINTER(timespec)]
    clock_gettime.restype = ctypes.c_int64    

    def time_ns():
        tmp = timespec()
        ret = clock_gettime(CLOCK_REALTIME, ctypes.pointer(tmp))
        if bool(ret):
            raise OSError()
        return tmp.tv_sec * 10 ** 9 + tmp.tv_nsec
```

**Comment by wtdcode** [comment]
I don't think depending on `libc.so.6` directly is a good way. Maybe we can re-implement that with `datetime` module.

**Comment by wtdcode** [comment]
Fixed in 902e01beb94e2e27e50d1456e51e0ef99937aff1
